### ISSUE TITLE
this is outdated and would benefit from an update, heres what i think would be nice to add:

### ISSUE THREAD

**Issue by ripooof** [mesalytic/discord-lookup-api#16]
connected accounts
bio
pronouns
nitro gradient
profile effect, & nitro badge
high quality banner link
premium since

additionally, being able to get the raw data received straight from discord would be nice

**Comment by mesalytic** [comment]
there will be a severe remake of the API, yes

however, I don't think all you said is properly available using the bot API, i'll check it though

**Comment by mesalytic** [comment]
I've added some of the features you asked, including the higher quality banner link as well as the raw data from Discord in this commit 481e01b750286b7716bfab17b3003ab596b1533f

I'll close it for now
