### ISSUE TITLE
API currently down

### ISSUE THREAD

**Issue by PatrykWalat** [mesalytic/discord-lookup-api#17]
It seems like the API doesnt work anymore?

**Comment by danilwhale** [comment]
:(

**Comment by PayDash** [comment]
yep :(

**Comment by mesalytic** [comment]
Hi everyone!
I'm currently out for vacation and didn't notice the API was actually down.

I'll look into it whenever I have free time, sorry for the inconvenience !

**Comment by Bluemethyst** [comment]
any updates on this? :P

**Comment by jSydorowicz21** [comment]
> any updates on this? :P

The PR I linked above allows you to deploy your own version of the API to vercel while waiting on mesalytic to get back from vacation and fix the production API. Please be patient, gotta remember that these are passion projects the devs aren't getting paid for :P

**Comment by Bluemethyst** [comment]
> > any updates on this? :P
> 
> The PR I linked above allows you to deploy your own version of the API to vercel while waiting on mesalytic to get back from vacation and fix the production API. Please be patient, gotta remember that these are passion projects the devs aren't getting paid for :P

I can't seem to see what you linked above... It's okay though I can set it up on vercel, thanks!

**Comment by jSydorowicz21** [comment]
> > > any updates on this? :P
> > 
> > 
> > The PR I linked above allows you to deploy your own version of the API to vercel while waiting on mesalytic to get back from vacation and fix the production API. Please be patient, gotta remember that these are passion projects the devs aren't getting paid for :P
> 
> I can't seem to see what you linked above... It's okay though I can set it up on vercel, thanks!

#18 Is the PR you're looking for!

**Comment by mesalytic** [comment]
> any updates on this? :P

Yep, the issue was network related, VPS has been restarted and the API should work like before!
