### ISSUE TITLE
Unauthorized?

### ISSUE THREAD

**Issue by PatrykWalat** [mesalytic/discord-lookup-api#19]
It might just be me but no matter the user ID i use it keeps showing 
`{
    "message": "401: Unauthorized",
    "code": 0
}`
https://[discordlookup.mesavirep.xyz/v1/user/121058722813444096](https://discordlookup.mesavirep.xyz/v1/user/121058722813444096)

**Comment by mesalytic** [comment]
No, this is not only you, it does this with other IDs
I'm currently looking onto it

**Comment by mesalytic** [comment]
It was a token issue, I reset it and it should work fine now
