### ISSUE TITLE
how to enable the "pretty print" with the api

### ISSUE THREAD

**Issue by Neyz0xx** [mesalytic/discord-lookup-api#21]
i wanted to add this api with a botghost bot with an embed but it write it without the "pretty print" writing i arleady ask in botghost support server but no one has an answer can you guys help me please

**Comment by mesalytic** [comment]
Hi, what do you mean by "pretty print" ?
The JSON value returned to be easier to read for humans?

**Comment by mesalytic** [comment]
No news, closing this until more info comes
