### ISSUE TITLE
snowflakeToDate is not a function on vercel selfhost

### ISSUE THREAD

**Issue by NotPiny** [mesalytic/discord-lookup-api#23]
Okay so i recently just setup a instance at https://discord-lookup-api-two.vercel.app/ but i tried to look up info on a user and got a FUNCTION_INVOCATION_FAILED in the log from vercel it said something about snowflakeToDate not being a function

```
Unhandled Rejection: TypeError: snowflakeToDate is not a function
    at /var/task/api/index.js:124:29
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
Node.js process exited with exit status: 128. The logs above can help with debugging the issue.
```

I have no clue what is causing this as i directly hit the deploy button within the readme and it works on the main instance so i would like to see this fixed if its a actual issue or how to fix it if i have somehow messed something up.

**Comment by mesalytic** [comment]
hi, sorry for the late response

this is probably linked to the recent commits, i'm checking what's going on

**Comment by mesalytic** [comment]
should be good :)
