### ISSUE TITLE
Use .env instead of config.json

### ISSUE THREAD

**Issue by haouarihk** [mesalytic/discord-lookup-api#4]
Reason:
env can be set in the enviroment, without needing a file in the working directory. which most services uses by default.

example:
```env
PORT=3000
TOKEN=PK_123456

// redis config
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=123
```

**Comment by mesalytic** [comment]
yep it's something I would need to do, I'll do it tomorrow when I find the time

**Comment by mesalytic** [comment]
done 👍 thanks for the suggestion
