### ISSUE TITLE
User Lookup sometimes returns undefined

### ISSUE THREAD

**Issue by AXOca** [mesalytic/discord-lookup-api#8]
As example: https://discordlookup.mesavirep.xyz/v1/user/1114010526817714296

btw. thank you so much for this API!

**Comment by mesalytic** [comment]
Mhh it’s weird I don’t seem to be able to reproduce it, even though it’s not the first time the issue has been reported, i guess it’s related to rate limit or something like that, definitely need to check it out

**Comment by AXOca** [comment]
btw

> Mhh it’s weird I don’t seem to be able to reproduce it, even though it’s not the first time the issue has been reported, i guess it’s related to rate limit or something like that, definitely need to check it out

Thank you! btw. I've tried to add you on discord but you sadly, do not accept friend requests. As I will do now, and probably in future ~5-50 API calls a day, I would love to donate something. Is there a way? :D

**Comment by mesalytic** [comment]
> > Mhh it’s weird I don’t seem to be able to reproduce it, even though it’s not the first time the issue has been reported, i guess it’s related to rate limit or something like that, definitely need to check it out
> 
> 
> 
> Thank you! btw. I've tried to add you on discord but you sadly, do not accept friend requests. As I will do now, and probably in future ~5-50 API calls a day, I would love to donate something. Is there a way? :D 

Enabled them, you should be able to send one now. It’s really nice of you for that, I’m only doing this for fun so it’s good if there isn’t any donos at the end ^^’

**Comment by AXOca** [comment]
Wonderful! Seems to be fixed.

**Comment by mesalytic** [comment]
Mh, didn’t do anything on it though lmao

I’ll still investigate if this is related to a rate-limit

**Comment by AXOca** [comment]
Hmm, I'm very new to programming - but I do not think, it's related to rate limitings. As once I were able to do about 100 API calls in 1 hour, and simply today I just tried to get 5 API Calls at once (which is less than usual) and it returned #undefined. 

idk. hopefully I'm helpful :D

**Comment by mesalytic** [comment]
i'll push a debug catch onto prod, returning raw errors if there are any as a response

i'm reopening the issue until something has been found

**Comment by mesalytic** [comment]
![issue](https://github.com/mesalytic/discord-lookup-api/assets/43297230/adf5ac19-8306-4c64-934f-19c9b2f202a8)

welp looks like I was on the right track
